openai:
  base_url: "https://api.openai.com"
  key: ""

wechat:
  app_id: ""
  app_secret: ""
  token: ""
  encoding_aes_key: ""

app:
  base_url: ""

storage: "memory" # memory or redis
redis:
  host: "redis"
  port: 6379
  password: ""