services:
  app:
    image: ghcr.io/k8scat/wechat-openai:latest
    ports:
      - 8080:8080
    volumes:
      - /path/to/config.yml:/app/config/config.yml
      - /path/to/logs:/app/logs
    container_name: wechat-openai

  redis:
    image: redis:7.0.10
    ports:
      - 6379:6379
    volumes:
      - /path/to/redis/data:/data
    container_name: wechat-openai-redis
    command:
      - redis-server
      - --appendonly yes
      - --save 60 1
